### ISSUE TITLE
The SQLiteSample runs an error after upgrading to .net5

### ISSUE THREAD

**Issue by Daoting** [unoplatform/Uno.sqlite-wasm#20]
The following is the configuration of the `SQLiteSample.Wasm.csproj`.
![无标题](https://user-images.githubusercontent.com/29876815/104271995-25929f80-54d7-11eb-9292-f9e96258ace3.png)

The project was built successfully, but the following exceptions are displayed at runtime:
```
uno-bootstrap.js:526 Debugging hotkey: Shift+Alt+D (when application has focus)
dotnet.js:2260 fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
dotnet.js:2260       The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.TextBox]
dotnet.js:2260 fail: Windows.UI.Xaml.Media.Animation.AddDeleteThemeTransition[0]
dotnet.js:2260       The member AddDeleteThemeTransition.AddDeleteThemeTransition() is not implemented in Uno.
dotnet.js:2260 fail: Windows.UI.Xaml.Media.Animation.ContentThemeTransition[0]
dotnet.js:2260       The member ContentThemeTransition.ContentThemeTransition() is not implemented in Uno.
dotnet.js:2260 fail: Windows.UI.Xaml.Media.Animation.ReorderThemeTransition[0]
dotnet.js:2260       The member ReorderThemeTransition.ReorderThemeTransition() is not implemented in Uno.
dotnet.js:2260 fail: Uno.UI.DataBinding.BindingPropertyHelper[0]
dotnet.js:2260       The [ScrollViewer] property getter does not exist on type [Windows.UI.Xaml.Controls.ListView]
dotnet.js:2272 
put_char @ dotnet.js:2272
dotnet.js:2272 Unhandled Exception:
put_char @ dotnet.js:2272
dotnet.js:2272 System.NullReferenceException: Arg_NullReferenceException
put_char @ dotnet.js:2272
dotnet.js:2272    at SQLitePCL.SQLite3Provider_dynamic_cdecl.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
put_char @ dotnet.js:2272
dotnet.js:2272    at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
put_char @ dotnet.js:2272
dotnet.js:2272    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
put_char @ dotnet.js:2272
dotnet.js:2272    at SQLitePCL.Batteries_V2.Init()
put_char @ dotnet.js:2272
dotnet.js:2272    at SQLite.SQLiteConnection..cctor()
put_char @ dotnet.js:2272
dotnet.js:2260 fail: Windows.UI.Core.CoreDispatcher[0]
dotnet.js:2260       Dispatcher unhandled exception
dotnet.js:2260 System.Exception: Failed to load SQLiteSample.MainPage: System.TypeInitializationException: TypeInitialization_Type, SQLite.SQLiteConnection
dotnet.js:2260  ---> System.NullReferenceException: Arg_NullReferenceException
dotnet.js:2260    at SQLitePCL.SQLite3Provider_dynamic_cdecl.SQLitePCL.ISQLite3Provider.sqlite3_libversion_number()
dotnet.js:2260    at SQLitePCL.raw.SetProvider(ISQLite3Provider imp)
dotnet.js:2260    at SQLitePCL.Batteries_V2.DoDynamic_cdecl(String name, Int32 flags)
dotnet.js:2260    at SQLitePCL.Batteries_V2.Init()
dotnet.js:2260    at SQLite.SQLiteConnection..cctor()
dotnet.js:2260    Exception_EndOfInnerExceptionStack
dotnet.js:2260    at SQLiteSample.MainPage.TryCreateDatabase() in D:\GitHub\Uno.Samples-master\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 53
dotnet.js:2260    at SQLiteSample.MainPage..ctor() in D:\GitHub\Uno.Samples-master\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\MainPage.xaml.cs:line 30
dotnet.js:2260    at SQLiteSample.Wasm.MetadataBuilder_613.CreateInstance() in D:\GitHub\Uno.Samples-master\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Wasm\Uno.UI.SourceGenerators\Uno.UI.SourceGenerators.BindableTypeProviders.BindableTypeProvidersSourceGenerator\BindableMetadata.cs:line 22389
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.CreatePageInstance(Type sourcePageType) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 420
dotnet.js:2260    at Windows.UI.Xaml.PagePool.DequeuePage(Type pageType) in C:\a\1\s\src\Uno.UI\UI\Xaml\PagePool.cs:line 69
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.CreatePageInstanceCached(Type sourcePageType) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 410
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 309
dotnet.js:2260    at SQLiteSample.App.OnNavigationFailed(Object sender, NavigationFailedEventArgs e) in D:\GitHub\Uno.Samples-master\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\App.xaml.cs:line 92
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.InnerNavigate(PageStackEntry entry, NavigationMode mode) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 369
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter, NavigationTransitionInfo infoOverride) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 262
dotnet.js:2260    at Windows.UI.Xaml.Controls.Frame.Navigate(Type sourcePageType, Object parameter) in C:\a\1\s\src\Uno.UI\UI\Xaml\Controls\Frame\Frame.cs:line 257
dotnet.js:2260    at SQLiteSample.App.OnLaunched(LaunchActivatedEventArgs e) in D:\GitHub\Uno.Samples-master\UI\SQLiteSample\SQLiteSample\SQLiteSample\SQLiteSample.Shared\App.xaml.cs:line 78
dotnet.js:2260    at Windows.UI.Xaml.Application.Initialize() in C:\a\1\s\src\Uno.UI\UI\Xaml\Application.wasm.cs:line 102
dotnet.js:2260    at Windows.UI.Core.CoreDispatcher.DispatchItems() in C:\a\1\s\src\Uno.UWP\UI\Core\CoreDispatcher.cs:line 310
WasmWebSockets.js:21 WebSocket connection to 'ws://172.21.144.1:58370/rc' failed: 
connect @ WasmWebSockets.js:21
WasmWebSockets.js:21 WebSocket connection to 'ws://172.19.0.1:58370/rc' failed: 
connect @ WasmWebSockets.js:21
WasmWebSockets.js:21 WebSocket connection to 'ws://10.10.1.16:58370/rc' failed: 
connect @ WasmWebSockets.js:21
dotnet.js:2260 fail: Uno.UI.RemoteControl.RemoteControlClient[0]
dotnet.js:2260       Failed to connect to the server (System.TimeoutException: Arg_TimeoutException
dotnet.js:2260          at Uno.UI.RemoteControl.RemoteControlClient.<StartConnection>d__12.MoveNext() in C:\a\1\s\src\Uno.UI.RemoteControl\RemoteControlClient.cs:line 127)

```

**Comment by jeromelaban** [comment]
Thanks for the report. You should not need either highlighted lines. The bootstrapper contains the latest release for the runtime, and the sqlite package works properly by choosing the appropriate bitcode file.

Why do you need to make those modifications ?

**Comment by Daoting** [comment]
It's just for testing, there's really no way. I upgraded all the nuget packages to the latest and had the same exception. It's the same as my project.
```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net5.0</TargetFramework>
    <!-- Because I have a slow Internet speed here, download the sdk first. -->
    <NetCoreWasmSDKUri>d:\dt\client\Common\wasm\dotnet-runtime-wasm-6c530cf-23391-Release.zip</NetCoreWasmSDKUri>
    <WasmHead>true</WasmHead>
    <DefineConstants>$(DefineConstants);__WASM__</DefineConstants>
    <NoWarn>NU1701</NoWarn>
	</PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <MonoRuntimeDebuggerEnabled>true</MonoRuntimeDebuggerEnabled>
    <DefineConstants>$(DefineConstants);TRACE;DEBUG</DefineConstants>
    <DebugType>portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="Assets\SplashScreen.png" />
    <EmbeddedResource Include="WasmCSS\Fonts.css" />
    <EmbeddedResource Include="WasmScripts\AppManifest.js" />
  </ItemGroup>
  <ItemGroup>
    <LinkerDescriptor Include="LinkerConfig.xml" />
  </ItemGroup>
  <ItemGroup>
    <None Include="Program.cs" />
    <None Include="LinkerConfig.xml" />
    <None Include="wwwroot\web.config" />
  </ItemGroup>
  <ItemGroup>
    <!-- Note that for WebAssembly version 1.1.1 of the console logger required -->
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Filter" Version="1.1.1" />
    <PackageReference Include="sqlite-net-pcl" Version="1.7.335" />
    <PackageReference Include="Uno.SQLitePCLRaw.provider.wasm" Version="3.0.14" />
    <PackageReference Include="Uno.UI.WebAssembly" Version="3.4.0" />
    <PackageReference Include="Uno.Wasm.Bootstrap" Version="2.0.0-dev.137" />
    <PackageReference Include="Uno.Wasm.Bootstrap.DevServer" Version="2.0.0-dev.137" />
    <PackageReference Include="Uno.UI.RemoteControl" Version="3.4.0" Condition="'$(Configuration)'=='Debug'" />
  </ItemGroup>

	<PropertyGroup>
		<CanUseAOT Condition="$([MSBuild]::IsOsPlatform('Linux')) or ( $([MSBuild]::IsOsPlatform('Windows')) and '$(BUILD_REPOSITORY_PROVIDER)'=='' )">true</CanUseAOT>
	</PropertyGroup>
  <ItemGroup Condition="'$(CanUseAOT)'==''">
    <PackageReference Update="Uno.SQLitePCLRaw.provider.wasm" Version="3.0.14" IncludeAssets="none" />
  </ItemGroup>
	
	<Import Project="..\SQLiteSample.Shared\SQLiteSample.Shared.projitems" Label="Shared" Condition="Exists('..\SQLiteSample.Shared\SQLiteSample.Shared.projitems')" />
</Project>
```

**Comment by jeromelaban** [comment]
At this point, there's an error somewhere in sqliteraw which does not support being run under .NET 5 Wasm. We'll try to find a solution in the future.

**Comment by Daoting** [comment]
Referring to your recent changes, I have done the following work:
1. Reference package SQLitePCLRaw.provider.sqlite3.
2. Use `SQLitePCL.raw.SetProvider(new SQLitePCL.SQLite3Provider_sqlite3());` SetProvider.
3. Change the e_sqlite3.bc to sqlite3.bc.

Sqlite can be used normally.

To save build time, I used the following methods:
1. Use `sqlite3.bc` as content. 
2. Put the generated `dotnet .js` `dotnet.wasm` into the dotnet-runtime package and replace the original files.
3. Specify the location of the new dotnet-runtime package through `NetCoreWasmSDKUri`.
4. Do not set `sqlite3.bc` as content.

I've tested it and I haven't found any problems yet. Since I don't know the principle, would you like to ask if this is possible? Thank you. @jeromelaban

**Comment by jeromelaban** [comment]
The change is done to run on .NET 5, but is not finished yet. Please continue using the previous bits as necessary.
